- project:
    templates:
      # FIXME: requirements need to be adapted to OpenStack
      # - check-requirements
      # FIXME: see https://review.opendev.org/747460
      # - lib-forward-testing-python3
      # FIXME: needs cover tox env
      # - openstack-cover-jobs
      # FIXME: add lower-constraints or drop this
      # - openstack-lower-constraints-jobs
      - openstack-python3-wallaby-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      # FIXME: prepare reno structures
      # - release-notes-jobs-python3
